#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_MAIN                                100
#define DLG_WIZARD                              110
#define IDR_MENU                                112
#define IDB_LOGO                                115
#define IDI_ICON                                119
#define DLG_ABOUT                               124
#define IDR_POPMOD                              128
#define IDB_MODENABLED                          130
#define IDB_MODDISABLED                         132
#define IDB_MODZIP                              134
#define IDB_MODDIR                              136
#define IDB_DNGRADE                             140
#define IDB_UPGRADE                             141
#define IDB_UPTODATE                            142
#define IDB_AVAILABLE                           143
#define DLG_GAME_ADD                            145
#define DLG_SNAP_CMP                            147
#define DLG_SNAP_NEW                            148
#define DLG_MOD_MAKE                            149
#define DLG_GAME_EDIT                           150
#define DLG_UNINSTALL                           153
#define DLG_REPOS_LST                           160
#define DLG_REPOS_UPD                           164
#define DLG_REPOS_XML                           166
#define BTN_ADD                                 40000
#define BTN_APPLY                               40000
#define CMB_GAMELIST                            40000
#define ENT_MAKEXMLPATH                         40000
#define ENT_SRC                                 40000
#define LVM_MODSUPDLIST                         40000
#define PBM_UNINST                              40000
#define TVS_REPOSLIST                           40000
#define TXT_GPL                                 40000
#define TXT_STATUS                              40000
#define BTN_ADDGAME                             40001
#define BTN_BROWSEMOD                           40001
#define BTN_BROWSESRC                           40001
#define ENT_MAKEXMLURL                          40001
#define PBM_DONWLOAD                            40001
#define TXT_COMMENT                             40001
#define TXT_UNINST_MOD                          40001
#define TXT_VERSION                             40001
#define BTN_MODCANCEL                           40002
#define CHK_CUSTBACKUP                          40002
#define ENT_REPOURL                             40002
#define ENT_VERSMAJOR                           40002
#define PBM_REPOQRY                             40002
#define TXT_TITLE                               40002
#define TXT_UNINST_GAME                         40002
#define BTN_CLOSE                               40003
#define BTN_IMPORTMOD                           40003
#define ENT_NAME                                40003
#define BTN_BROWSEDST                           40004
#define BTN_REPOADD                             40004
#define ENT_BACKPATH                            40004
#define ENT_OUTPUT                              40004
#define LVM_MODSLIST                            40004
#define TXT_REPOQRYSTATUS                       40004
#define BTN_BROWSEXMLPATH                       40005
#define BTN_CREATE                              40005
#define BTN_MODDIS                              40005
#define BTN_REPOREM                             40005
#define PBM_SNAP_CMP                            40005
#define PBM_SNAP_NEW                            40005
#define TXT_REPOQRYURL                          40005
#define BTN_BROWSEBCK                           40006
#define BTN_MAKEXMLSAVE                         40006
#define BTN_QUIT                                40006
#define PBM_MAKE                                40006
#define TXT_DOWNSPEED                           40006
#define BTN_BROWSEROOT                          40007
#define BTN_CANCEL                              40007
#define BTN_MODENA                              40007
#define CHK_CUSTXMLPATH                         40007
#define ENT_VERSMINOR                           40007
#define BTN_MAKEXMLSRC                          40008
#define BTN_REPOUPDALL                          40008
#define ENT_DST                                 40008
#define ENT_ROOTPATH                            40008
#define PBM_MODPROC                             40008
#define BTN_REPOUPDSEL                          40009
#define ENT_MODSPATH                            40009
#define ENT_VERSREVIS                           40009
#define ENT_MODDESC                             40010
#define BTN_REPORETRY                           40011
#define CB_ZIPLEVEL                             40011
#define MNU_ABOUT                               40040
#define MNU_GAMEADD                             40041
#define MNU_GAMEEDIT                            40042
#define MNU_GAMEREM                             40043
#define MNU_MODDIS                              40044
#define MNU_MODENA                              40045
#define MNU_MODIMPORT                           40046
#define MNU_MODCREATE                           40048
#define MNU_HELP                                40049
#define MNU_MODDISALL                           40050
#define MNU_MODENAALL                           40051
#define MNU_SNAPCOMPARE                         40052
#define MNU_SNAPCREATE                          40053
#define MNU_PROFILELOAD                         40054
#define MNU_PROFILSAVE                          40055
#define MNU_REPOSCONFIG                         40056
#define MNU_REPOSQUERY                          40057
#define MNU_REPOSMKXML                          40058
#define POP_OPENDIR                             40062
#define POP_TOGGLE                              40065
#define POP_ENABLE                              40066
#define POP_DISABLE                             40067
